# -*- coding: utf-8 -*-
"""KAGGLE STUDY_(20.03.17) X²-TEST

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L7XHgnKDzh2-TMvOSxb9PvxxfWMJ_0zk

# X²-검정 - 확률과 독립의 검정
<br>
<br>

## X²- 검정이란 ? 

> 범주별로 관측된 빈도와 기대빈도의 차이를 봄으로써
<br>
> 하나의 확률모형이 전반적으로 자료를 얼마나 잘 설명하는지 검정하는데 사용
> 3개 이상의 범주가 존재 및 상자의 내용의 구성이 알려졌을 때 사용

> ※ z-검정 or t-검정 ? 2개의 범주만 존재, 상자의 평균만 주어져 있을 때 사용
"""

from IPython.display import Image
Image('./sample_data/x1.PNG')

"""## 확률과 독립의 검정 (EX) 왼손잡이라는 특성이 성별과 독립인가?)

 > 검정의 순서 

 1. 성별 및 사용하는 손의 결합분포(도수) 및 조건부분포(비율) 확인
 2. 표본 2,237명이 모집단으로부터 무작위 추출되었다고 가정하고 상자모형 설정
 3. 범주별 관측된 도수와 기대도수 계산
 4. 범주별 관측된 도수와 기대도수의 차이를 이용하여 X²-통계량 구하기 ※ 자유도
 5. 자유도가 2인 X²- 분포 곡선에서 X²-통계량에 해당하는 p-값 확인 후 독립 여부 판정

####  1. 성별 및 사용하는 손의 결합분포(도수) 및 조건부 분포(비율)
<br>

> 전체 데이터가 6개로, 2 * 2가 아닌 2 * 3 table이라 X²- 검정 필수 !  

> 표본 2,237명이 모집단으로부터 무작위 추출되었다고 가정

> 귀무가설 : 성별과 오른손/왼손/양손잡이 여부는 독립이다 - > 비율 차이도 표본추출 과정에서 우연이다

> 대립가설 : 실질적인 관계가 있다 -> 모집단에서의 실제 차이를 반영한다.

> 유의수준 : 0.5%
"""

from IPython.display import Image
Image('./sample_data/x2.PNG')

"""> <_R_> 결합분포?(Joint distribution) <-> Marginal

> <_Q_> 어떻게 조건부분포(비율)로 나타낼까? 조건 부여 / 한정 / Focus를 통해 오른손잡이&남성/ 전체남성수

#### 2. 표본 2,237명이 모집단으로부터 무작위 추출되었다고 가정하고 상자모형 설정
"""

from IPython.display import Image
Image('./sample_data/x3.PNG')

"""#### 3. 범주별 관측된 도수와 기대도수 계산

  ※ 비율을 모르니, 표본으로 추출한 값으로 대체

> EX) P(오른손잡이) ? 독립이라는 가정하에 - 
<br>
      (934+1027)/2237 -> 0.896 => 89.6%
<br>
      => 전체 표본크기 2237명에 대한 기대도수 계산 가능
"""

from IPython.display import Image
Image('./sample_data/x4.PNG')

Image('./sample_data/x4_2.PNG')

"""#### 4. 범주별 관측된 도수와 기대도수의 차이를 이용하여 X²-통계량 구하기 ※ 자유도"""

from IPython.display import Image
Image('./sample_data/x5.PNG')

"""#### 5. 자유도가 2인 X²- 분포 곡선에서 X²-통계량에 해당하는 p-값 확인 후 독립 여부 판정"""

from IPython.display import Image
Image('./sample_data/x6.PNG')

"""#  실제 적용해보기 [파이썬/코드]

: 제품의 판매량 비율은 다음과 같습니다. A 56%, B 12%, C 32% 
<br>

그런데, 특정 지역에 제품 A, B, C의 보유대수를 조사하니, 각각 324대, 78대, 261대였습니다.
<br>

이 자료로 다음과 같이 관찰빈도와 기대빈도를 만들 수 있습니다.



> 1) 하나의 변수만 포함된 일원 카이제곱검정(one-way chi-squared test)

> 2) 이원 카이제곱검정(two-way chi-squared test)
<br>
> : 제품1 ~ 3까지 여성과 남성의 판매량 차이에 대하여 카이제곱검정을
"""

# Commented out IPython magic to ensure Python compatibility.
from pandas import DataFrame

xo, xe = [324, 78, 261], [371, 80, 212]
xc = DataFrame([xo, xe], columns=['Item A', 'Item B', 'Item C'], index=['Obs', 'Exp'])
print(xc)

import matplotlib.pyplot as plt
# %matplotlib inline

ax = xc.plot(kind='bar', title='Number of Items', figsize=(8, 6))
ax.set_ylabel('value')
plt.grid(color='darkgray')
plt.show()

from scipy.stats import chisquare

result = chisquare(xo, f_exp=xe)
print(result)

# => p-value가 0.0001725로 유의수준 0.05보다 아주 작은 값이므로 귀무가설을 기각합니다.

# 이원 카이제곱검정(two-way chi-squared test) 
# 제품1 ~ 3까지 여성과 남성의 판매량 차이에 대하여 카이제곱검정 

xf, xm = [269, 83, 215], [155, 57, 181]
x = DataFrame([xf, xm], columns=['Item 1', 'Item 2', 'Item 3'], index=['Female', 'Male'])
print(x)
print()

from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency([xf, xm])

msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi2, p, dof))
print(expected)

# p-value는 0.02881으로 유의수준 0.05보다 작은 값입니다. 2개 그룹 간에 차이가 있다고 판단

"""# 참고 사이트
> https://m.blog.naver.com/PostView.nhn?blogId=parksehoon1971&logNo=221589203965&proxyReferer=https%3A%2F%2Fwww.google.com%2F

>  https://whatisthenext.tistory.com/106
"""

from IPython.display import Image
Image('./sample_data/x7.PNG')

