# -*- coding: utf-8 -*-
"""KAGGLE STUDY_Probability(2020.02.18)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQJlv6Dh4JdMRHaw9t7ykLNNqen1rIkz

(KAGGLE STUDY_2020.02.18/화) 

# 확률이란 무엇인가


---
<br>
<br>

> # 확률? 확률의 특성?  
<br>
 - 확률이란?
 - 확률의 특성?
<br> 
   : 0% ~ 100% 사이의 값을 가진다.
<br>
     -> A가 일어날 확률이 P(A)이면, 일어나지 않을 확률은 1 - P(A) 
<br>
<br>
> *벤 다이어그램(직사각형과 그 안에 든 원을 이용하여 사건을 나타내는 그림) 
<br>
> ** 배반? 한 사건 발생 -> 다른 사건이 함께 발생할 수 없는 경우

<br>
<br>

> #  조건부확률 P(A|B) ?
> #  주변확률P(A), P(B)? 
> #  결합확률(P(A and B/곱셈법칙)?
> #  독립? 
<br>

> ### 조건부확률 P(A|B) <-> 주변부 확률 P(A), P(B) ( x에 대한 정보 이용 X) 
<br>
> '조건'이란? 정보(Ex. X값) 이용하는 것으로 보다 Focus할 수 있는 단서가 됨 
<br>

> Regression? 조건부 분포 묘사할 때, 
<br> 
> 각각 조건부 분포가 어떻게 직선으로 근사되는지 알려줌 -> x값에 따라 y값을 보겠다는 뜻 !  
<br>

> ### 결합확률(joint probability) -> P(A and b)

> 두 사건이 함께 일어날 확률 = 곱셈법칙

> P(A) * P(B|A) or P(B) * P(A|B)


> ### 독립(하나의정보가 다른 정보에 전혀 도움 X) -> P(A and B) = P(A)P(B)
"""

from IPython.display import Image

Image('p1.PNG')

# [1] 비조건 무작위 1명 추출 시 남학생인 확률은?
# [2] 비조건 무작위 추출한 100명의 흡연율은?
# [3] 무작위 한명 추출 시 흡연하며, 남학생일 확률은?
# [4] 무작위 추출하여 남학생이면서 흡연자일 확률 
# => 정보의 역할 : FOCUS = 단서 
# 30/100 , 30./45,  45/100, 60/100

Image('p2.PNG')

# 결합확률, 곱셈법칙식을 그림으로 나타낸다면?
# P(A and B) = P(A) * P(B|A)

